[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[workspace]
members = ["programs/escrow"]

[programs.devnet]
escrow = "9MtY5vEpJCf31Ak19wfJ25Ef5bdVvs9nzoxeh3yEf4FB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --manifest-path programs/escrow/Cargo.toml"
